### ISSUE TITLE
Ticking entity crash due to changes to Beckon in Scape and Run: Parasites 1.9.1

### ISSUE THREAD

**Issue by zediious** [zediious/galacticdrive#15]
## Bug description

The new Scape and Run: Parasites version (1.9.1) introduced changes to the Stage I > II evolution of Beckons (ground tendrils) This appears to have introduced a crash that occurs when a Stage I Beckon grows into a Stage II Beckon. After being in the world (Roika) for about 30 minutes, which is enough time for a Beckon to evolve, a crash occurs due to a ticking entity (Venkrol, which is the class name for Beckons)

## Did this behavior work in a previous version?

This did not occur before SR Parasites v1.9.1

## Steps to reproduce

1: Load a new world
2: Sit in the world for roughly 30 minutes
3: Crash due to ticking entity, which preceded by huge TPS drops

NOTE: This can be avoided by clearing all entities when the TPS drop is noticed. Obviously not a solution but a stop-gap.

## Logs
Logs can be found within the instance installation folder within the `logs` folder. 
Then upload latest.log (or a previous log where the bug occurred) to Pastebin or Gist.-->
* Client/Server Log: [Client/Server crashlog](https://gist.github.com/zediious/d423297f1b973fe9ee37a23988b71635)

## Client information
* Modpack Version: 0.2alpha
* Java Version: Java 8
* Launcher Used: MultiMC
* Memory Allocated: 8192M
* Singleplayer/Server: Singleplayer/Server
* Server API: None

**Comment by zediious** [comment]
This seems to be at least partially caused by the following configuration in SRParasites.cfg

`# Maximum Stage a Beckon can grow up in a Dimension. Ex. "1;3"  Where: 
    #  "1" is for the dimension, 
    #  "3" is for the stage it cannot grow up. 
    #  [default: [1;3]]
    S:"Reinforcement System Maximum Stage" <
        -500;4
        0;4
        -1;4
        17;4
        -127;4
        111;4
        112;4
        4598;4
     >`

Normally, Roika (-500) is set to not allow the Beckon to grow past Stage I as it is a starter planet. This configuration option appears to not be updated correctly to respect the new Beckon growth system. Allowing Stage 4 on Roika bypasses this crash, although it is not how the planet is meant to me nor how that option is meant to behave.

Issue will remain open until the issue is resolved.

**Comment by zediious** [comment]
Latest version of SR Parasites seems to fix this issue. Issue will be closed when update is in 0.2alpha branch

[https://www.curseforge.com/minecraft/mc-mods/scape-and-run-parasites/files/3728258](https://www.curseforge.com/minecraft/mc-mods/scape-and-run-parasites/files/3728258)

`Crash:
java.lang.IllegalArgumentException: bound must be positive
at java.util.Random.nextInt(Unknown Source)
at com.dhanantry.scapeandrunparasites.entity.ai.EntityPVenkrol.setGT(EntityPVenkrol.java:75)`

**Comment by zediious** [comment]
Fixed via [https://github.com/zediious/galacticdrive/pull/14/commits/f0970d7923c38d7aa4ccfda0c196a547cdba1684](https://github.com/zediious/galacticdrive/pull/14/commits/f0970d7923c38d7aa4ccfda0c196a547cdba1684)

**Comment by zediious** [comment]
Fix present in new release https://github.com/zediious/galacticdrive/releases/tag/0.2.1
